### ISSUE TITLE
Grunde til salg

### ISSUE THREAD

**Issue by Nyborg1** [Nyborg1/nyborg_gis#24]
**Grunde til salg** skal opbygges i det nye WebGIS - GC2 / VIDI.
Dels skal der opsættes ny hjemmeside med relevante tekster og billeder. 
Limbo  har gjort det muligt at bruge embed.js kort-element i Umbraco-cms-systemet. 

1.  Data er overført overført til database **nyborg_gis._13_06_02_salg_af_jord.grundsalg_grund2**
2.  konfiguration "grundsalg" er oprettet
3.  Opsætning af editering i VIDI / GC2
4.  Drift og brug af system

**Comment by Nyborg1** [comment]
link til nyborg.dk - gammelt system som udfases (KortInfo)

**Comment by Nyborg1** [comment]
Hvilken css-file bruges i grundsalg? "_grundsalg.css" ?
Den der ligger i Github?

#test {
}
#find-me-btn,
#burger-btn,
#full-screen-btn,
#about-btn,
#session,
#legend-dialog,
#place-search,
#mapcontrols-history-backward,
#mapcontrols-history-forward,
#session,
#zoom-default-btn
{
  display:none !important;
}
#fixed-table-container fixed-height{
  height: 100px
}

**Comment by Larsklindt** [comment]
Hej Peter.

Jeg har haft fjernet den midlertidigt fordi den fjernede muligheden for at jeg kunne logge ind på vidi..



Med venlig hilsen

Lars Klindt
GIS-konsulent

Mobil +45 2858 1660
***@***.***

Rugårdsvej 55 A
5000 Odense C
CVR 20014784

***@***.***<https://geopartner.dk/>
***@***.***<https://geopartner.us13.list-manage.com/subscribe?u=b5e29f1bf557180ca3a432529&id=aaa47e9bd0>
Geopartner Landinspektører A/S' ydelser leveres i henhold til vores forretningsbetingelser<https://geopartner.dk/forretningsbetingelser/>
og i overensstemmelse med vores persondatapolitik<persondatapolitik.geopartner.dk>
Fra: Peter Jørgensen ***@***.***>
Sendt: 6. december 2022 08:48
Til: Nyborg1/nyborg_gis ***@***.***>
Cc: Lars Klindt ***@***.***>; Assign ***@***.***>
Emne: Re: [Nyborg1/nyborg_gis] Grunde til salg (Issue #24)


Hvilken css-file bruges i grundsalg? "_grundsalg.css" ?
Den der ligger i Github?

#test {
}
#find-me-btn,
#burger-btn,
#full-screen-btn,
#about-btn,
#session,
#legend-dialog,
#place-search,
#mapcontrols-history-backward,
#mapcontrols-history-forward,
#session,
#zoom-default-btn
{
display:none !important;
}
#fixed-table-container fixed-height{
height: 100px
}

—
Reply to this email directly, view it on GitHub<https://url12.mailanyone.net/scanner?m=1p2ShC-0000yC-6C&d=4%7Cmail%2F90%2F1670312400%2F1p2ShC-0000yC-6C%7Cin12f%7C57e1b682%7C18971197%7C7315417%7C638EF3E6A39B9E914E5657F019A3A4AA&o=%2Fphti%3A%2FgtsmbthNco%2Fu.nrybb1%2Fyog%2F_orsisigg%23ssus24ie%2Fecsutmmneo63-13916388&s=Zoq8KA9xKIsmn_DB5X5mjLbz7kw>, or unsubscribe<https://url12.mailanyone.net/scanner?m=1p2ShC-0000yC-6C&d=4%7Cmail%2F90%2F1670312400%2F1p2ShC-0000yC-6C%7Cin12f%7C57e1b682%7C18971197%7C7315417%7C638EF3E6A39B9E914E5657F019A3A4AA&o=%2Fphti%3A%2Fgtsmbthnco%2Fu.tfotocaiiibunscsus%2Fnteri%2Fauhb-C7AG4L6GNM3VO5ROJGJZUWRZA3VZTLAFNCAM6ANSHRAAE7YFAG&s=EIB8GLSnQWK-rzEFZe3KnyAi2RU>.
You are receiving this because you were assigned.Message ID: ***@***.***>

________________________________

Denne e-mail er blevet scannet for at stoppe evt. spam og virus. Hvis du mener, at denne besked burde have blevet stoppet, skal du klikke her<https://portal.mailanyone.net/index.html#/outer/reportspam?token=dXNlcj1sa21AZ2VvcGFydG5lci5kazt0cz0xNjcwMzEyOTM1O3V1aWQ9NjM4RUYzRTZBMzlCOUU5MTRFNTY1N0YwMTlBM0E0QUE7dG9rZW49MjYwZjA5MjkxYTgyNmFlOTVhZjJjYWIwYmE4ZGQzOTgxNzljODg1ZDs%3D> for at rapportere beskeden som spam.

**Comment by Nyborg1** [comment]
Kan det hele styres uden css?
